package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.buildSteps.ScriptBuildStep
import jetbrains.buildServer.configs.kotlin.v2019_2.buildSteps.dockerCommand
import jetbrains.buildServer.configs.kotlin.v2019_2.buildSteps.script
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'Build'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("Build")) {
    expectSteps {
        script {
            name = "NPM"
            scriptContent = "npm install"
            dockerImagePlatform = ScriptBuildStep.ImagePlatform.Linux
            dockerPull = true
            dockerImage = "node:current-alpine3.11"
        }
        dockerCommand {
            commandType = push {
                namesAndTags = "gcr.io/trove-equity/node-app:new"
            }
        }
    }
    steps {
        insert(2) {
            dockerCommand {
                name = "Push"
                commandType = push {
                    namesAndTags = "gcr.io/trove-equity/node-app:new"
                }
            }
        }
    }
}
