 steps:
  - name: gcr.io/k8s-skaffold/pack
    args:
      - build
      - '$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA'
      - '--builder=gcr.io/trove-equity/builder'
      - '--path=functions'
      - '--env=GOOGLE_FUNCTION_TARGET=index'
      - '--env=GOOGLE_RUNTIME=nodejs'
    id: Buildpack
    entrypoint: pack
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - '$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA'
    id: Push
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    args:
      - '-c'
      - >
        gcloud run services update $_SERVICE_NAME --platform=managed
        --image=$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
        --labels=managed-by=gcp-cloud-build-deploy-cloud-run,commit-sha=$COMMIT_SHA,gcb-build-id=$BUILD_ID,gcb-trigger-id=$_TRIGGER_ID,$_LABELS
        --region=$_DEPLOY_REGION --update-env-vars=SOME_SECRET=$$SOME_SECRET
        --quiet
    id: Deploy
    entrypoint: bash
    secretEnv:
      - SOME_SECRET
images:
  - '$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA'
options:
  substitutionOption: ALLOW_LOOSE
substitutions:
  _SERVICE_NAME: pave-test
  _DEPLOY_REGION: us-central1
  _GCR_HOSTNAME: us.gcr.io
  _LABELS: gcb-trigger-id=ca26e228-cd68-4f73-8d78-825bf7cd21f6
  _TRIGGER_ID: ca26e228-cd68-4f73-8d78-825bf7cd21f6
  _PLATFORM: managed
tags:
  - gcp-cloud-build-deploy-cloud-run
  - gcp-cloud-build-deploy-cloud-run-managed
  - pave-web
availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/test_secret/versions/latest
      env: SOME_SECRET