
version: 2.1

orbs:
  node: circleci/node@4.1

jobs:
  build-and-test:  
    docker:
      - image: gcr.io/trove-equity/circle-tf-gcp-k8s:latest
        auth:
          username: "_json_key"
          password: $GCLOUD_SERVICE_KEY

    steps:
      - setup_remote_docker:
          version: 19.03.13
      - checkout
      - run: echo $GCLOUD_SERVICE_KEY > service_key.json
      - run: export GOOGLE_APPLICATION_CREDENTIALS="$(pwd)/service_key.json" >> $BASH_ENV
      - run: npm install
      - run: docker build . -t gcr.io/trove-equity/node-app:"$CIRCLE_SHA1"
      - run: |
          echo $GCLOUD_SERVICE_KEY | gcloud auth activate-service-account $GCLOUD_SERVICE_ACCOUNT --key-file=-
          gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
          gcloud --quiet config set compute/zone ${GOOGLE_COMPUTE_ZONE}
      - run: gcloud auth configure-docker
      - run: docker push gcr.io/trove-equity/node-app:"$CIRCLE_SHA1"
      - run: GOOGLE_APPLICATION_CREDENTIALS="$(pwd)/service_key.json" bash -c "cd terraform && terraform init && terraform plan"

workflows:
  sample: 
    jobs:
      - build-and-test:
          context:
            - "Google"

