version: 2.1

orbs:
  node: circleci/node@4.1

jobs:
  build-and-test:  
    machine: true
    steps:
      - checkout
      - run: npm install
      - run:
          name: Run tests
          command: npm test
      - run: docker build . -t gcr.io/trove-equity/jenkins:"$CIRCLE_SHA1"
  deploy:
    docker:
          - image: google/cloud-sdk
            auth:
              username: mydockerhub-user
              password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run: echo $GCLOUD_SERVICE_KEY
      - run: |
          echo $GCLOUD_SERVICE_KEY | gcloud auth activate-service-account --key-file=-
          gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
          gcloud --quiet config set compute/zone ${GOOGLE_COMPUTE_ZONE} 

workflows:
  sample: 
    jobs:
      - build-and-test
      - deploy
